### PR TITLE
feat(seekbar, volume): add the ability to control the direction of se…

### PR DESCRIPTION
**Pull request by jspizziri**
…ek and volume PanResponders

### CODE REVIEW

**Comment by jspizziri** [comment]
The purpose of this PR is to allow for the control of the PanReponders in the event a transformation has occurred on the video player view.

As a specific example, we support fullscreen mode via an animated style transformation on a view wrapping the video player. When the device is in a Landscape orientation the player is either under a `90deg` or `-90deg` rotation. As it currently stands the PanResponders don't like this as they currently only support panning along the `x` axis, however, we now need to pan on the `y`. Moreover,  you need the ability to control the inversion of the responder in these situations as well given the negative or positive direction of rotation.

Would love feedback, and thanks for the lib.

**Comment by jspizziri** [comment]
@LunatiqueCoder any thoughts on this? It's not super pressing for me as I've published my fork to npm, but I would love to not have to use a fork :).

**Comment by LunatiqueCoder** [comment]
Ahh sorry, I was so busy lately. I'll try again this week. 🙈 Sorry for the inconvenience.

The code looks good, I just have to test it. 👌

**Comment by jspizziri** [comment]
no apologies needed!

**Comment by jspizziri** [comment]
Just a friendly ping on this.

**Review by LunatiqueCoder — APPROVED** [review]

**Comment by LunatiqueCoder** [comment]
Thank you very much! I didn't test it very carefully, but it looks good.

**Pull request merged**
