### PR TITLE
[+] Replace disableSeekbar with disableSeekBar

### PR DESCRIPTION
**Pull request by esegebart**
[+] Disable seek bar was not working

VideoPlayerProps were being passed as disableSeekBar to the the variable disableSeekbar and was not disabling it properly. Changed the prop to capitalize the B everywhere and in documentation and now all is working :) Also tested and it disables it properly now.

### CODE REVIEW

**Comment by esegebart** [comment]
@esegebart Did I need to make an issue ticket for this? I guess I don't know the protocol if I find a bug :)

**Comment by LunatiqueCoder** [comment]
@esegebart It's nice to have, but not a requirement. We're the only active maintainers so we can decide together. 

Sorry for the summer time being quite inactive. I'll try to have a better look this weekend or the next 🙈

**Comment by esegebart** [comment]
@LunatiqueCoder You do not need to apologize :) Glad you are enjoying your summer. Like you said, it's open source, there is no rush 😎

**Comment by LunatiqueCoder** [comment]
Not sure what's the issue here, but `disableSeekbar` seems to be working for me? I'm afraid to change the naming because it will introduce a little breaking change 

What else can you tell me about this issue? 🤔

**Comment by esegebart** [comment]
Oh! It was not working on Android. I couldn't disable the seekbar. When the
object was returned - it returned disableSeekBar and the variable it was
trying to be set to was disableSeekbar. So it was always false and never
got set true. So I changed them all to disableSeekBar in the project to try
and avoid any breaking changes. :( but I guess it broke it still?

**Comment by LunatiqueCoder** [comment]
@esegebart Oh, ok then, I think it's better to change them all to `disableSeekbar' - this way it will not introduce breaking changes for the users. Do you want me to do this change or perhaps you want to improve your contribution stats on the repository? 😂

**Comment by esegebart** [comment]
I think that is what I thought I did in this pull request is replace them
all? Is that not true?

**Comment by esegebart** [comment]
Oh! Ok you want them to be the other way. I will send over here in 10 min!

**Comment by esegebart** [comment]
@LunatiqueCoder Wait no bc then that will make it break again for Android. The Android object returned has disableSeekBar - and disableSeekbar did not work. So I'd be putting it back to the way it was when it was broken

**Comment by LunatiqueCoder** [comment]
@esegebart hmm, this is weird, i'm wondering where is this Android object coming from? 🤔 Is it from the `props`?

**Comment by LunatiqueCoder** [comment]
@esegebart It seems to me that you might be setting `disableSeekBar` yourself from a parent component. I couldn't find any inconsistency in this project 🙈 `disableSeekBar` doesn't exist at all in the project.

**Comment by esegebart** [comment]
@LunatiqueCoder Yes in the VideoPlayerProps

**Comment by LunatiqueCoder** [comment]
@esegebart I think we should jump in google meet, perhaps with a shared screen we can also share ideas easier?

**Comment by esegebart** [comment]
I'll have to look at the comparisons again to verify what I'm saying, I'm
headed back to work now and I'll take a look. Maybe it was!

**Comment by LunatiqueCoder** [comment]
@esegebart Don't worry, no pressure! I'll start being more active now :)

**Comment by esegebart** [comment]
Well, I know I'm not crazy. I hadn't changed anything and I had to hunt
down why it was not setting the disableSeekbar to true. It remained false.
I'm trying to remember the object I was console logging. Will let you know.

**Comment by LunatiqueCoder** [comment]
@esegebart You're not using TypeScript on your project right?

**Comment by esegebart** [comment]
No, I am not :(

**Comment by LunatiqueCoder** [comment]
@esegebart Then you are not crazy, but you are not using TypeScript either haha. This is one of those things that TypeScript does, it makes you write more code, but it enforces you to use it better and with less bugs 😌

If you can confirm everything works well for you if you use `disableSeekbar` everywhere, I suppose we can close this?

**Comment by esegebart** [comment]
Yes I will have more time to confirm this tomorrow and will message you!

**Comment by LunatiqueCoder** [comment]
@esegebart Any news with this one? Does `disableSeekbar` work for you?

**Comment by LunatiqueCoder** [comment]
I'll close this one for now, will reopen if needed. Trying to clean up a little bit.

**Comment by esegebart** [comment]
So sorry! I got very busy. :( I believe you if you say you did not find
anything with it. I may have just overlooked something or it was being set
myself, I am not sure. When I get some time to circle back with it, I will
let you know :)

**Pull request closed without merging**
