### PR TITLE
Seekbar controls feature

### PR DESCRIPTION
**Pull request by esegebart**
Added skip forward and skip backward icons to move 15 seconds ahead or back. 
Changed the rewind and fast forward buttons to continuously skip upon pressing. Each press increase the speed of rewind or fast forward up to 4X.

### CODE REVIEW

**Comment by esegebart** [comment]
@LunatiqueCoder The last commit will be necessary to try it out. I had also forgotten to remove an import so it will break without last commit. :)

**Comment by LunatiqueCoder** [comment]
Ok, I'll **try** to have a look this weekend. Really happy that you mananged to sort it out!

**Comment by esegebart** [comment]
Me too! Thank you! :)

**Comment by LunatiqueCoder** [comment]
@esegebart Ok, this looks good actually, but of course it can be improved. And It just came to my mind a very good idea. Although I have 1 question: 

Do you plan to have both type of buttons for your project? Or do you want to keep the ones you created only? Because I think that https://github.com/LunatiqueCoder/react-native-media-console/issues/37 will enable you to extract your logic outside of the package and pass it as props (onPressRewind, icon, etc), meaning that everyone will be able to customise to an extended level.

**Comment by esegebart** [comment]
@LunatiqueCoder Hey! I'm so glad you like it 🤩 So in my case, yes, I will be using both. Some of my broadcasts are 12 hours long so I need to be able to allow the user to get to a game that starts at 8 hours in quickly, while also letting them go back 15 seconds to rewatch a play made by a player. In the future, this my not be necessary because the cameras will know when a new game starts. But I was just trying to figure out how to separate those concerns between skipping and rewind/fast forwarding. And voila! Two buttons :) Did you try the continuous rewind/FF up to 4x? I actually discovered how to do it by accident. 😂 It would be nice to have a little indicator how fast they are at but yeah! Super glad to hear it looks good!

**Comment by LunatiqueCoder** [comment]
Hey @esegebart. Does this work on your side? I tried it on iOS and it's going a little bit crazy 🥲

**Comment by esegebart** [comment]
I haven't tested it in a while. I will have to check it out and get back to
you!

**Pull request closed without merging**
