### PR TITLE
Prop alwaysShowControls

### PR DESCRIPTION
**Pull request by leadmrn**
Hi,

I created a new prop which allows to display the controls for the entire duration of the media included. It can be useful for audio media that has no visual content for example.

It's up to you whether you want to include it or not!

### CODE REVIEW

**Comment by criszz77** [comment]
Hey!

I realy liked everything you came up with so far - I'm sure I'll like this one as well.

Do you need help resolving conflicts? 

if you need any help contributing, this comment might help: https://github.com/criszz77/react-native-media-console/issues/49#issuecomment-1414058736

**Comment by leadmrn** [comment]
Ok that's good normally!

**Comment by criszz77** [comment]
Okay, @leadmrn,  looks good, I'll test them this weekend and will definitely have this!

About the bugs, it's worth mentioning that some of them are from [`react-native-video`](https://github.com/react-native-video/react-native-video). They are working on version 6 and they have a release candidate. I'm personally using that version since it fixes a lot of bugs. 

You can try it with the [alpha version](https://github.com/react-native-video/react-native-video#installing-version-600-alphas) using `yarn add react-native-video@alpha` or `npm install --save react-native-video@alpha`

**Comment by leadmrn** [comment]
No worries, the pleasure is mine.

For the bugs I had already installed react-native-video v6 and it didn't fix the problems :/

**Comment by criszz77** [comment]
All right, good to know. I'll check it out this weekend and have it merged. Again, thanks a lot!

**Comment by LunatiqueCoder** [comment]
All right, I checked this one and I think it's very good. One thing I'm not sure about is the name. I'm thinking about something like `disableControlsToggle` and also mention in the README file that it should be used with `showOnStart={true/false}` to force the controls into a `shown` or `hidden` state. What do you think?

**Review by LunatiqueCoder — APPROVED** [review]

**Pull request merged**
